### ISSUE TITLE
Wrap setting of environment vars in an if check for Meteor.settings

### ISSUE THREAD

**Issue by widespaceDLS** [themeteorchef/building-a-user-admin#3]
I downloaded this repo ~building-a-user-admin~ , installed locally here:  C:\mA\chefUA 
Checked all package dependencies, project seems complete.

Same error came up at  ~ base ~ :
https://github.com/themeteorchef/base/commit/54c1c1debfc9d5fff4696f7db57393e092d57e91

But there is different context here, in ~building-a-user-admin~
I'm new to meteor and javascript too .. so can only guess what to suggest.

=> Exited with code: 8
W20151031-00:21:30.429(-4)? (STDERR)     at _setEnvironmentVariables (server/modules/startup.js:10:34)
W20151031-00:21:30.429(-4)? (STDERR) TypeError: Cannot read property 'MAIL_URL' of undefined
W20151031-00:21:30.425(-4)? (STDERR)
W20151031-00:21:30.428(-4)? (STDERR)                                            throw(ex);
W20151031-00:21:30.427(-4)? (STDERR) C:\Users\TEC\AppData\Local.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20151031-00:21:30.431(-4)? (STDERR)     at C:\mA\chefUA.meteor\local\build\programs\server\boot.js:249:5
W20151031-00:21:30.428(-4)? (STDERR)                                                  ^
W20151031-00:21:30.430(-4)? (STDERR)     at Object.startup (server/modules/startup.js:2:3)
W20151031-00:21:30.430(-4)? (STDERR)     at server/startup.js:1:38

**Comment by themeteorchef** [comment]
@widespaceDLS thanks for noting this. This is the same error you mentioned in Base. I've updated Base with a fix for this, however, need to update this repo, too. In the meantime, you can start your server with `meteor --settings settings-development.json`—or, `npm start`—and it will fix this error.

Going to flag this as a bug and get it in the queue for a fix.
